version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "EST5EDT"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
