version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[ci skip]"
