# From conda-forge-pinning
zip_keys:
  -
    - python
    - numpy

python:
  # part of a zip_keys: python, numpy
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython

numpy:
  # part of a zip_keys: python, numpy
  - 2.0
  - 2.0
  - 2.0
  - 2.0

pybind11_abi:
  - 4
