# From conda-forge-pinning
zip_keys:
  -
    - python
    - numpy

python:
  # part of a zip_keys: python, numpy
#  - 3.8.* *_cpython
#  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython

numpy:
  # part of a zip_keys: python, numpy
#  - 1.22
#  - 1.22
  - 1.22
  - 1.23
  - 1.26

pybind11_abi:
  - 4
