{% set name = "hoomd" %}
{% set version = "4.5.0" %}
{% set build = 0 %}
{% set sha256 = "b44f3dc9aa6b60c6bb5fe7c668d72af7eb1a52a4ebf5abe1849e9bb92da88667" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  string: {{ cluster }}_{{ device }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script: bash ${RECIPE_DIR}/build_hoomd.sh {{ device }}

#  rpaths:
#    - lib/
#    - lib/python3.12/site-packages/{{ name }}  # [py==312]
#    - lib/python3.11/site-packages/{{ name }}  # [py==311]
#    - lib/python3.10/site-packages/{{ name }}  # [py==310]
#    - lib/python3.9/site-packages/{{ name }}  # [py==39]

requirements:
  build:
    - cmake
    - ninja
    - pkg-config

  host:
    - cereal
    - eigen
    - numpy
    - pybind11
    - pybind11-abi
    - python

  run:
    - python
    - numpy

test:
  requires:
    - pytest
    - rowan
  imports:
    - hoomd
    - hoomd.md
    - hoomd.hpmc
# pytest hangs for unknown reasons on Great Lakes
#  commands:
#    - pytest --pyargs hoomd -v
